# Generated by Django 3.0.10 on 2020-11-14 16:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Game title')),
                ('version', models.CharField(max_length=10, verbose_name='Game Version')),
                ('description', models.TextField(verbose_name='Game describtion')),
                ('min_users', models.PositiveSmallIntegerField(verbose_name='Minimum User number')),
                ('max_users', models.PositiveSmallIntegerField(verbose_name='Maximum User number')),
                ('extra_info', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Additional information of Game')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(default=False, verbose_name='Game status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('gameinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_rooms', to='games.GameInfo', verbose_name='Game information')),
            ],
        ),
    ]
