# Generated by Django 3.0.10 on 2020-11-15 16:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='gameroom',
            name='setting',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Additional setting for GameRoom'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='type',
            field=models.CharField(choices=[('GE', 'General'), ('PR', 'Practice'), ('RA', 'Ranking')], default='GE', max_length=2, verbose_name='Game Type'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='status',
            field=models.CharField(choices=[('NS', 'Not started'), ('FN', 'Finished'), ('EO', 'Error occured')], default='NS', max_length=2, verbose_name='Game status'),
        ),
    ]
