# Generated by Django 3.1.3 on 2020-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201116_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinfo',
            name='extra_info',
            field=models.JSONField(verbose_name='Additional information of Game'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='setting',
            field=models.JSONField(blank=True, default=dict, verbose_name='Additional setting for GameRoom'),
        ),
    ]
