# Generated by Django 3.1.3 on 2020-12-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201203_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameroom',
            old_name='setting',
            new_name='extra_setting',
        ),
        migrations.RemoveField(
            model_name='gameroom',
            name='status',
        ),
        migrations.AddField(
            model_name='gameversion',
            name='default_setting',
            field=models.JSONField(default=dict, verbose_name='Version default setting'),
        ),
        migrations.CreateModel(
            name='GameMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.JSONField(blank=True, default=dict, verbose_name='History in Game Match')),
                ('score', models.IntegerField(blank=True, default=0, verbose_name='Match Score')),
                ('status', models.CharField(choices=[(None, '(Unknown)'), ('NS', 'Not started'), ('FN', 'Finished'), ('EO', 'Error occured')], default='NS', max_length=2, verbose_name='Game Match Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameroom_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_matchs', to='games.gameroom', verbose_name='Game room')),
            ],
        ),
    ]
