# Generated by Django 3.1.3 on 2020-12-13 03:45

import algo_sports.games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201205_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameversion',
            name='default_setting',
            field=models.JSONField(default=algo_sports.games.models.get_default_setting, verbose_name='Version default setting'),
        ),
    ]
