# Generated by Django 3.1.3 on 2020-12-13 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20201213_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamematch',
            name='status',
            field=models.CharField(choices=[(None, '(Unknown)'), ('NS', 'Not started'), ('IN', 'In progress'), ('FN', 'Finished'), ('EO', 'Error occured')], default='NS', max_length=2, verbose_name='Game Match Status'),
        ),
    ]
