version: "3"

services:
  django: &django
    logging:
      driver: awslogs
      options:
        awslogs-group: algo-sports
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: django

  nginx:
    logging:
      driver: awslogs
      options:
        awslogs-group: algo-sports
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: nginx
    depends_on:
      - django

  redis:
    image: redis:5.0

  celeryworker:
    <<: *django
    logging:
      driver: awslogs
      options:
        awslogs-group: algo-sports
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: celeryworker

  flower:
    <<: *django
    logging:
      driver: awslogs
      options:
        awslogs-group: algo-sports
        awslogs-region: ap-northeast-2
        awslogs-stream-prefix: flower
