# Generated by Django 3.1.3 on 2020-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20201119_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.SlugField(unique=True, verbose_name='Blog cateogry'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Blog description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post title'),
        ),
    ]
