# Generated by Django 3.1.3 on 2020-11-20 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_auto_20201120_1723'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRoomRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Game score')),
                ('history', models.JSONField(verbose_name='Game history')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gameroom_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gameroom')),
            ],
            options={
                'db_table': 'code_room_relation',
            },
        ),
        migrations.CreateModel(
            name='UserCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=30, verbose_name='Programming language')),
                ('code', models.TextField(verbose_name='Submitted code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gamerooms', models.ManyToManyField(related_name='usercodes', through='codes.CodeRoomRelation', to='games.GameRoom')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JudgementCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=30, verbose_name='Programming language')),
                ('code', models.TextField(verbose_name='Submitted code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gameinfo_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='judgement_codes', to='games.gameinfo', verbose_name='Game information')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='coderoomrelation',
            name='usercode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.usercode'),
        ),
    ]
