# Generated by Django 3.0.10 on 2020-11-13 01:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("games", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserCode",
            fields=[
                ("usercode_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "programming_language",
                    models.CharField(
                        max_length=30, verbose_name="Programming language"
                    ),
                ),
                ("code", models.TextField(verbose_name="Submitted code")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JudgementCode",
            fields=[
                (
                    "judgementcode_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                (
                    "programming_language",
                    models.CharField(
                        max_length=30, verbose_name="Programming language"
                    ),
                ),
                ("code", models.TextField(verbose_name="Submitted code")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "gameinfo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="judgement_codes",
                        to="games.GameInfo",
                        verbose_name="Game information",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GameCodes",
            fields=[
                ("gamecodes_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(verbose_name="Game score")),
                (
                    "history",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        verbose_name="Game history"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gameroom_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="games.GameRoom"
                    ),
                ),
                (
                    "usercode_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="codes.UserCode"
                    ),
                ),
            ],
        ),
    ]
