# Generated by Django 3.1.3 on 2020-11-20 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='Programming language')),
            ],
        ),
        migrations.AlterField(
            model_name='judgementcode',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.programminglanguage', verbose_name='Programming language'),
        ),
        migrations.AlterField(
            model_name='usercode',
            name='programming_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.programminglanguage', verbose_name='Programming language'),
        ),
    ]
