# Generated by Django 3.0.10 on 2020-11-16 01:43

import algo_sports.utils.fileds
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecodes',
            name='history',
            field=algo_sports.utils.fileds.JSONField(verbose_name='Game history'),
        ),
    ]
