# Generated by Django 3.0.10 on 2020-11-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20201116_2014'),
        ('codes', '0002_crossdb_jsonfield'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCodes',
            new_name='CodeRoomRelation',
        ),
        migrations.AlterModelTable(
            name='coderoomrelation',
            table='code_room_relation',
        ),
    ]
