# Generated by Django 3.1.3 on 2020-11-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0002_add_programming_language_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is code active?'),
        ),
    ]
