# Generated by Django 3.1.3 on 2020-12-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_usercode_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderoomrelation',
            name='history',
            field=models.JSONField(default=dict, verbose_name='Game history'),
        ),
        migrations.AlterField(
            model_name='coderoomrelation',
            name='score',
            field=models.IntegerField(default=0, verbose_name='Game score'),
        ),
    ]
