# Generated by Django 3.0.10 on 2020-11-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_auto_20201116_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coderoomrelation',
            old_name='finished_at',
            new_name='updated_at',
        ),
    ]
