# Generated by Django 3.1.3 on 2020-11-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_auto_20201117_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coderoomrelation',
            name='history',
            field=models.JSONField(verbose_name='Game history'),
        ),
    ]
