# Generated by Django 3.1.3 on 2020-12-05 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201205_0158'),
        ('codes', '0005_auto_20201205_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchCodeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('gamematch_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.gamematch')),
            ],
            options={
                'db_table': 'match_code_relation',
            },
        ),
        migrations.RemoveField(
            model_name='usercode',
            name='gamerooms',
        ),
        migrations.DeleteModel(
            name='CodeRoomRelation',
        ),
        migrations.AddField(
            model_name='matchcoderelation',
            name='usercode_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='codes.usercode'),
        ),
        migrations.AddField(
            model_name='usercode',
            name='gamematchs',
            field=models.ManyToManyField(related_name='usercodes', through='codes.MatchCodeRelation', to='games.GameMatch'),
        ),
    ]
