# Generated by Django 3.1.3 on 2020-12-06 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201205_0158'),
        ('codes', '0006_auto_20201205_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='gameroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usercodes', to='games.gameroom'),
            preserve_default=False,
        ),
    ]
