# Generated by Django 3.1.3 on 2020-12-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201205_0158'),
        ('codes', '0007_usercode_gameroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judgementcode',
            name='gameinfo_id',
        ),
        migrations.AddField(
            model_name='judgementcode',
            name='gameversion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='judgement_codes', to='games.gameversion', verbose_name='Game version'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usercode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is code active?'),
        ),
    ]
