# Generated by Django 3.1.3 on 2020-12-15 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20201213_1433'),
        ('codes', '0012_programminglanguage_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercode',
            name='gamerooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usercodes', to='games.gameroom'),
        ),
    ]
